import Head from "next/head";
import { useEffect, useState } from "react";
import Login from "@/components/Login";
import Notes from "@/components/Notes";

export default function Home() {
  const [user, setUser] = useState(null);

//   // Logout logic
  const handleLogout = () => {
    localStorage.removeItem("token");
    setUser(null);
  };


  useEffect(() => {
    if (localStorage.getItem("token")) {
      setUser({}); // Just a placeholder, actual user info can be fetched if needed
    }
},[]);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='center-card'>
      {!user
        ? <Login onLogin={setUser} />
        : (
            <div>
              <button className="btn" onClick={handleLogout} style={{float:'right'}}>Logout</button>
              <Notes />
            </div>
          )
      }
    </div>
    </>
  );
}
